### ISSUE TITLE
Lay-out issues Chrome

### ISSUE THREAD

**Issue by freddy-db** [wimvanhouts/cc-world-wide-merch#14]
<img width="1196" alt="image" src="https://github.com/wimvanhouts/cc-world-wide-merch/assets/137878222/278679fa-5251-4644-b1b2-35407979e536">

Chrome 114, MacOS 13.4.1

**Comment by bart-nnx** [comment]
Problem with loading the assets. Depends on the URL you use:
* Not working: https://www.peej.ai/cc
* Working: https://www.peej.ai/cc/ (notice the trailing slash)

Probably not an issue for the PROD release but I'll have a look.

**Comment by bart-nnx** [comment]
Fixed! Kijk jij even of het nu wel voor je werkt @freddy-db? Probeer met een incognito window a.j.b.

**Comment by freddy-db** [comment]
Lijkt gefixt!
