### ISSUE TITLE
Submit button in fotosjop text is out of boundaries on desktop view 

### ISSUE THREAD

**Issue by wimvanhouts** [wimvanhouts/cc-world-wide-merch#2]
![image](https://github.com/wimvanhouts/cc-world-wide-merch/assets/12234274/81a8ebc1-61e9-4adc-9ce9-4b67b209a4e5)

**Comment by bart-nnx** [comment]
Done!

Op mobiel:
![image](https://github.com/wimvanhouts/cc-world-wide-merch/assets/135689218/5986c082-d23a-40df-b28a-ccfdbd5d3074)

Op desktop:
![image](https://github.com/wimvanhouts/cc-world-wide-merch/assets/135689218/01ba7bae-2a2b-4117-843d-0555e4291f63)
